<div id="wrapper">
<input type="button" value="change style" id="styleButton"/>
	<nav>
		<ul id="navigation">

				<a id ="profileShortcut" href="./index.php" style="display:block;"></a>
			<li><a href="./">Home</a></li>
			<li><a href="./#projecten">Projects</a></li>
			<li><a href="./#about">About</a></li>
			<li><a href="./#contact">Contact</a></li>
			<li class="selected"><a href="./dirtest.php">HKU</a></li>
		</ul>
	</nav>
	<section class="content">